FROM node:7.4.0-slim

RUN groupadd -r nodejs && useradd -m -r -g nodejs nodejs
USER nodejs

# FROM node:6.9.4-alpine

# RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
# USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app
# mounted and installed when run

EXPOSE 8000
EXPOSE 58580

CMD ["npm", "run", "develop"]
