FROM node:7.4.0-alpine

# for uws
RUN apk add --update libc6-compat && rm -rf /var/cache/apk/*

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app
# mounted and installed when run

EXPOSE 3000
EXPOSE 5858

CMD ["npm", "run", "develop"]
