version: "2"
services:
  admin_web:
    image: decider/admin_web:development
    build:
      context: ./admin_web
      dockerfile: Dockerfile.development
    volumes:
        - ./admin_web:/home/nodejs/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ADMIN_API_URL=http://192.168.64.16:3001 # TODO: remove hard coding

  admin_api:
    image: decider/admin_api:development
    build:
      context: ./admin_api
      dockerfile: Dockerfile.development
    volumes:
        - ./admin_api:/home/nodejs/app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
