FROM node:alpine

# git for lerna
# libc6-compat for uws
RUN apk add --update git libc6-compat && rm -rf /var/cache/apk/*

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app
# mounted and installed when run

CMD ["npm", "run", "dist"]
