FROM node:alpine

# git for lerna
# libc6-compat for uws
RUN apk add --update git libc6-compat && rm -rf /var/cache/apk/*

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app

COPY package.json /home/nodejs/app/package.json
RUN npm install --dev --production
COPY ./server /home/nodejs/app/server

COPY lerna.json /home/nodejs/app/lerna.json
COPY ./packages /home/nodejs/app/packages
USER root
RUN node_modules/.bin/lerna bootstrap --hoist --ignore api-web-application
USER nodejs

EXPOSE 3000

CMD ["npm", "run", "start"]
