FROM node:7.4.0-alpine

RUN apk add --update bash && rm -rf /var/cache/apk/*

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app

COPY package.json /home/nodejs/app/package.json
RUN npm install --production
COPY ./server /home/nodejs/app/server
COPY ./public /home/nodejs/app/public

EXPOSE 3000

CMD ["npm", "run", "start"]
