version: "2"
services:
  admin_web:
    image: decider/admin_web:develop
    build:
      context: ../../admin_web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../admin_web:/home/nodejs/app
    ports:
      - "3000:3000"
    env_file:
      - environments/admin_web.production.env
    command: npm run compile
