version: "2"
services:
  admin_web:
    image: decider/admin_web:develop
    build:
      context: ../../containers/admin_web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../containers/admin_web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - ADMIN_API_URL=http://192.168.64.16:3001 # TODO: remove hard coding
    command: npm run start-debug

  admin_api:
    image: decider/admin_api:develop
    build:
      context: ../../containers/admin_api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../containers/admin_api:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run start-debug
