version: "2"
services:
  image_web:
    image: decider/image_web:develop
    build:
      context: ../../image_web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image_web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - environments/image_web.development.env

  image_read_api:
    image: decider/image_read_api:develop
    build:
      context: ../../image_read_api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image_read_api:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - environments/image_read_api.development.env

  image_command_api:
    image: decider/image_command_api:develop
    build:
      context: ../../image_command_api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image_command_api:/home/nodejs/app
    ports:
      - "3002:3000"
      - "5860:5858"
    env_file:
      - environments/image_command_api.development.env
