version: "2"
services:
  image-web:
    image: decider/image-web:develop
    build:
      context: ../../image-web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image-web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - environments/image-web.development.env

  image-read-api:
    image: decider/image-read-api:develop
    build:
      context: ../../image-read-api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image-read-api:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - environments/image-read-api.development.env

  image-command-api:
    image: decider/image-command-api:develop
    build:
      context: ../../image-command-api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image-command-api:/home/nodejs/app
    ports:
      - "3002:3000"
      - "5860:5858"
    env_file:
      - environments/image-command-api.development.env
