version: "2"
services:
  admin_web:
    image: decider/admin_web:develop
    build:
      context: ../../admin_web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../admin_web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - environments/admin_web.development.env

  admin_api:
    image: decider/admin_api:develop
    build:
      context: ../../admin_api
      dockerfile: Dockerfile.develop
    volumes:
        - ../../admin_api:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - environments/admin_api.development.env
