version: "2"
services:
  image-web:
    image: decider/image-web:develop
    build:
      context: ../../image-web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image-web:/home/nodejs/app
    env_file:
      - environments/image-web.production.env
    command: npm run dist
