version: "2"
services:
  image_web:
    image: decider/image_web:develop
    build:
      context: ../../image_web
      dockerfile: Dockerfile.develop
    volumes:
        - ../../image_web:/home/nodejs/app
    env_file:
      - environments/image_web.production.env
    command: npm run dist
