version: "2"
services:
  image_web:
    image: decider/image_web:pack
    build:
      context: ../../image_web
      dockerfile: Dockerfile.pack
    ports:
      - "3000:3000"
    env_file:
      - environments/image_web.production.env

  image_read_api:
    image: decider/image_read_api:pack
    build:
      context: ../../image_read_api
      dockerfile: Dockerfile.pack
    ports:
      - "3001:3000"
    env_file:
      - environments/image_read_api.production.env

  image_command_api:
    image: decider/image_command_api:pack
    build:
      context: ../../image_command_api
      dockerfile: Dockerfile.pack
    ports:
      - "3002:3000"
    env_file:
      - environments/image_command_api.production.env
