version: "2"
services:
  admin_web:
    image: decider/admin_web:pack
    build:
      context: ../../containers/admin_web
      dockerfile: Dockerfile.pack
    volumes:
        - ../../containers/admin_web:/home/nodejs/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_API_URL=http://192.168.64.16:3001 # TODO: remove hard coding

  admin_api:
    image: decider/admin_api:pack
    build:
      context: ../../containers/admin_api
      dockerfile: Dockerfile.pack
    volumes:
        - ../../containers/admin_api:/home/nodejs/app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
