version: "2"
services:
  web:
    image: decider/web:dist
    build:
      context: ../../web
      dockerfile: Dockerfile.dist
    ports:
      - "3000:3000"
    env_file:
      - environments/web.production.env

  api-read:
    image: decider/api-read:dist
    build:
      context: ../../api-read
      dockerfile: Dockerfile.dist
    ports:
      - "3000:3000"
    env_file:
      - environments/api-read.production.env

  api-command:
    image: decider/api-command:dist
    build:
      context: ../../api-command
      dockerfile: Dockerfile.dist
    ports:
      - "3000:3000"
    env_file:
      - environments/api-command.production.env
