version: "2"
services:
  admin_web:
    image: decider/admin_web:pack
    build:
      context: ../../admin_web
      dockerfile: Dockerfile.pack
    ports:
      - "3000:3000"
    env_file:
      - environments/admin_web.production.env

  admin_api:
    image: decider/admin_api:pack
    build:
      context: ../../admin_api
      dockerfile: Dockerfile.pack
    ports:
      - "3001:3000"
    env_file:
      - environments/admin_api.production.env
