version: "2"
services:
  image-web:
    image: decider/image-web:pack
    build:
      context: ../../image-web
      dockerfile: Dockerfile.pack
    ports:
      - "3000:3000"
    env_file:
      - environments/image-web.production.env

  image-read-api:
    image: decider/image-read-api:pack
    build:
      context: ../../image-read-api
      dockerfile: Dockerfile.pack
    ports:
      - "3001:3000"
    env_file:
      - environments/image-read-api.production.env

  image-command-api:
    image: decider/image-command-api:pack
    build:
      context: ../../image-command-api
      dockerfile: Dockerfile.pack
    ports:
      - "3002:3000"
    env_file:
      - environments/image-command-api.production.env
