version: "2"
services:
  decider:
    image: decider/decider:dev
    build:
      context: ../../../..
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
        - ../../../..:/home/nodejs/app
    depends_on:
      - "eventstore"
      - "mongodb"
      - "rabbitmq"
    env_file:
      - ../environments/decider.env

  eventstore:
    image: decider/eventstore:dev
    build:
      context: ../../../../images/eventstore
      dockerfile: Dockerfile.dev
    ports:
      - "1113:1113"
      - "2113:2113"

  mongodb:
    image: decider/mongodb:dev
    build:
      context: ../../../../images/mongodb
      dockerfile: Dockerfile.dev
    ports:
      - "27017:27017"

  rabbitmq:
    image: decider/rabbitmq:dev
    build:
      context: ../../../../images/rabbitmq
      dockerfile: Dockerfile.dev
    ports:
      - "5672:5672"
