version: "2"
services:
  web:
    image: decider/web:dev
    build:
      context: ../../../../images/web
      dockerfile: Dockerfile.dev
    volumes:
        - ../../../../images/web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - ../environments/web.env

  api-read:
    image: decider/api-read:dev
    build:
      context: ../../../../images/api-read
      dockerfile: Dockerfile.dev
    volumes:
        - ../../../../images/api-read:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - ../environments/api-read.env

  api-command:
    image: decider/api-command:dev
    build:
      context: ../../../../images/api-command
      dockerfile: Dockerfile.dev
    volumes:
        - ../../../../images/api-command:/home/nodejs/app
    ports:
      - "3002:3000"
      - "5860:5858"
    env_file:
      - ../environments/api-command.env
