version: "2"
services:
  web:
    image: decider/web:dev
    build:
      context: ../../web
      dockerfile: Dockerfile.dev
    volumes:
        - ../../web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - environments/web.development.env

  api-read:
    image: decider/api-read:dev
    build:
      context: ../../api-read
      dockerfile: Dockerfile.dev
    volumes:
        - ../../api-read:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5859:5858"
    env_file:
      - environments/api-read.development.env

  api-command:
    image: decider/api-command:dev
    build:
      context: ../../api-command
      dockerfile: Dockerfile.dev
    volumes:
        - ../../api-command:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5860:5858"
    env_file:
      - environments/api-command.development.env
