version: "2"
services:
  web:
    image: decider/web:dev
    build:
      context: ../../../../images/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - ../environments/web.env
    volumes:
        - ../../../../images/web:/home/nodejs/app

  api:
    image: decider/api:dev
    build:
      context: ../../../../images/api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - ../environments/api.env
    volumes:
        - ../../../../images/api:/home/nodejs/app
    depends_on:
      - "eventstore"

  eventstore:
    image: decider/eventstore:dev
    build:
      context: ../../../../images/eventstore
      dockerfile: Dockerfile.dev
    ports:
      - "1113:1113"
      - "2113:2113"
