version: "2"
services:
  web:
    image: decider/web:dev
    build:
      context: ../../../../images/web
      dockerfile: Dockerfile.dev
    volumes:
        - ../../../../images/web:/home/nodejs/app
    ports:
      - "3000:3000"
      - "5858:5858"
    env_file:
      - ../environments/web.env

  api:
    image: decider/api:dev
    build:
      context: ../../../../images/api
      dockerfile: Dockerfile.dev
    volumes:
        - ../../../../images/api:/home/nodejs/app
    ports:
      - "3001:3000"
      - "5859:5858"
    env_file:
      - ../environments/api.env
