version: "2"
services:
  web:
    image: decider/web:dev
    build:
      context: ../../../../images/web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
        - ../../../../images/web:/home/nodejs/app
    env_file:
      - ../environments/web.env

  api:
    image: decider/api:dev
    build:
      context: ../../../../images/api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
      - "5859:5858"
    volumes:
        - ../../../../images/api:/home/nodejs/app
    depends_on:
      - "eventstore"
      - "mongodb"
      - "rabbitmq"
    env_file:
      - ../environments/api.env

  servicebus:
    image: decider/servicebus:dev
    build:
      context: ../../../../images/servicebus
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
      - "5860:5858"
    volumes:
        - ../../../../images/servicebus:/home/nodejs/app
    depends_on:
      - "rabbitmq"
    env_file:
      - ../environments/servicebus.env

  mongodb:
    image: decider/mongodb:dev
    build:
      context: ../../../../images/mongodb
      dockerfile: Dockerfile.dev
    ports:
      - "27017:27017"

  rabbitmq:
    image: decider/rabbitmq:dev
    build:
      context: ../../../../images/rabbitmq
      dockerfile: Dockerfile.dev
    ports:
      - "5672:5672"

  eventstore:
    image: decider/eventstore:dev
    build:
      context: ../../../../images/eventstore
      dockerfile: Dockerfile.dev
    ports:
      - "1113:1113"
      - "2113:2113"
