#!/bin/bash

tag=pack
namespace=decider

dir=`dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]})`; cd $(dirname $(dirname $(dirname $dir)))

eval $(minikube docker-env)
path=$(pwd)
if [ -f $path/Dockerfile.$tag-dist ]; then
  file=${path##*/}
  file="$(echo $file | tr [:upper:] [:lower:])"
  docker rmi $(docker images -q $namespace/$file:$tag-dist) -f || true
fi

path=$(pwd)
if [ -f $path/Dockerfile.$tag ]; then
  file=${path##*/}
  file="$(echo $file | tr [:upper:] [:lower:])"
  docker rmi $(docker images -q $namespace/$file:$tag) -f || true
fi

docker rmi $(docker images --quiet --filter "dangling=true") -f || true
