#!/bin/bash

tag=pack
namespace=decider
dir=`dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]})`

eval $(docker-machine env)
ls -d images/* | while read path; do
  if [ -f $path/Dockerfile.$tag-dist ]; then
    file=${path##*/}
    docker rmi $(docker images -q $namespace/$file:$tag-dist) -f || true
  fi
done

eval $(minikube docker-env)
ls -d images/* | while read path; do
  file=${path##*/}
  docker rmi $(docker images -q $namespace/$file:$tag) -f || true
done

docker rmi $(docker images --quiet --filter "dangling=true") || true
