#!/bin/bash

env=production
dir=`dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]})`

eval $(minikube docker-env)
ls -d scripts/local/production/cluster/* | while read path; do
  kubectl delete -f $path
done
kubectl delete namespace $env
