#!/bin/bash

kubectl delete -f scripts/local/production/cluster/api-command-deployment.json
kubectl delete -f scripts/local/production/cluster/api-command-service.json
kubectl delete -f scripts/local/production/cluster/api-read-deployment.json
kubectl delete -f scripts/local/production/cluster/api-read-service.json
kubectl delete -f scripts/local/production/cluster/web-deployment.json
kubectl delete -f scripts/local/production/cluster/web-service.json
kubectl delete -f scripts/local/production/cluster/local-forwarding-service.json
kubectl delete namespace dist
