#!/bin/bash

env=production

dir=`dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]})`; cd $(dirname $(dirname $(dirname $dir)))

eval $(minikube docker-env)
kubectl create namespace $env
ls -d scripts/local/production/cluster/* | while read path; do
  kubectl create -f $path
done
