FROM node:7.4.0-alpine

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /app
WORKDIR /app

COPY package.json /app/package.json
# RUN npm install --production
RUN npm install
COPY . /app

EXPOSE 3000
EXPOSE 3001

CMD ["npm", "run", "startDev"]
