FROM node:4.7.1

# Alpine is not supported
# https://github.com/meteor/meteor/issues/4573
# FROM node:4.7.1-alpine

# install meteor
RUN curl https://install.meteor.com/ | sh

# Alpine is not supported
# RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
RUN groupadd -r nodejs && useradd -m -r -g nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app
# mounted and installed when run

EXPOSE 3000
EXPOSE 5858

# download meteor
RUN meteor update --all-packages

CMD ["npm", "run", "develop"]
