#!/bin/bash

eval "$(minikube docker-env)"
kubectl delete -f deploy/image-command-api-deployment.json
kubectl delete -f deploy/image-command-api-service.json
kubectl delete -f deploy/image-read-api-deployment.json
kubectl delete -f deploy/image-read-api-service.json
kubectl delete -f deploy/image-web-deployment.json
kubectl delete -f deploy/image-web-service.json
