#!/bin/bash

kubectl create -f deploy/api-command-deployment.json
kubectl create -f deploy/api-command-service.json
kubectl create -f deploy/api-read-deployment.json
kubectl create -f deploy/api-read-service.json
kubectl create -f deploy/web-deployment.json
kubectl create -f deploy/web-service.json
