#!/bin/bash

tag=dev
namespace=decider

dir=`dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]})`; cd $(dirname $(dirname $(dirname $dir)))

# docker rmi $(docker images --quiet --filter "dangling=true") || true
docker stop $(docker ps -a -q) || true
docker rm $(docker ps -a -q) -f || true
docker rmi $(docker images -q) -f || true
