FROM node:7.5.0-alpine

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app

COPY package.json /home/nodejs/app/package.json
RUN npm install --dev --production
COPY ./server /home/nodejs/app/server

EXPOSE 3000

CMD ["npm", "run", "start"]
