FROM node:7.5.0-alpine

RUN addgroup nodejs && adduser -s /bin/bash -D -G nodejs nodejs
USER nodejs

RUN mkdir -p /home/nodejs/app
WORKDIR /home/nodejs/app
# mounted and installed when run

CMD ["npm", "run", "dist"]
